### ISSUE TITLE
Cùng chọn đê

### ISSUE THREAD

**Issue by KienThinhPN** [KienThinhPN/Lop-10A01-Nhom-5#3]
tìm thành ngữ / tục ngữ / ca dao hoặc thơ phù hợp để diễn tả được suy nghĩ trong bài làm

**Comment by KienThinhPN** [comment]
Giờ thì tìm ca dao tục ngữ thôi nha, làm bài thì chờ khi nào kêu làm thì làm

**Comment by VinhNguyen1612** [comment]
tục ngữ về chủ đề j cũng được ak :>

**Comment by KienThinhPN** [comment]
J cũng được ai thích câu nào cứ đóng góp ý kiến

**Comment by KienThinhPN** [comment]
Có vẻ chưa ai tìm ra câu nào nên t xung phong trước vậy. T đề xuất câu “Luyện mãi thành tài, miệt mài tất giỏi”

**Comment by KienThinhPN** [comment]
hoàn toàn không phải là t đang cày game mà thích câu này nhá ┐(´∀｀)┌

**Comment by QuachAiNhu10A01** [comment]
hiện tại trong đầu t mới chỉ nghĩ ra câu "Vỏ quýt dày có móng tay nhọn/ Kẻ cắp gặp bà già" thôi à :((

**Comment by QuachAiNhu10A01** [comment]
hay là câu này cũng hay nè 
"Ngọc kia chẳng giũa chẳng mài
Cũng thành vô dụng cũng hoài ngọc đi."

**Comment by VinhNguyen1612** [comment]
kiếm được mấy câu hay đó :)) để t kiếm thêm

**Comment by VinhNguyen1612** [comment]
t cũng tìm ra mấy câu dễ dễ :>
"Có công mài sắt, có ngày nên kim."
"Cái khó ló cái khôn"
"Chị ngã, em nâng."
"Cây muốn lặng mà gió chẳng dừng."
"Một cây làm chẳng nên non ba cây chụm lại nên hòn núi cao"
"Một điều nhịn chín điều lành ."
"Một giọt máu đào hơn ao nước lã."

**Comment by VinhNguyen1612** [comment]
ủa còn j nữa ko z :))

**Comment by VinhNguyen1612** [comment]
ủa chưa có j để làm hả m :>?

**Comment by VinhNguyen1612** [comment]
bữa con Hân nói nó làm cái j đó cho bên nhóm nó mà sao bên mình chill v :>

**Comment by HienCaoPhuNhuan** [comment]
rồi sao ko thấy mấy đứa chốt gì hết trơn vậy
